on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
      - name: Setup Virtual Environment
        run: make venv
      - name: Run CLI Tests
        run: make ci