on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.11
      - name: Setup Virtual Environment
        run: make venv
      - name: Run CLI Tests
        run: make ci